name: Auto-Configure Branch Protection

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  configure-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Configure Branch Protection
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.repos.updateBranchProtection({
                owner: 'consultasiarteq-commits',
                repo: 'oposia',
                branch: 'main',
                required_status_checks: {
                  strict: true,
                  contexts: []
                },
                enforce_admins: true,
                required_pull_request_reviews: {
                  required_approving_review_count: 1,
                  dismiss_stale_reviews: true,
                  require_code_owner_reviews: false
                },
                restrictions: null,
                required_linear_history: false,
                allow_force_pushes: false,
                allow_deletions: false
              });
              console.log('? Branch protection configured successfully');
            } catch (error) {
              console.error('? Error configuring branch protection:', error.message);
              core.setFailed('Failed to configure branch protection');
            }
