name: Configuración Automática de Protección de Ramas

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  setup-branch-protection:
    runs-on: ubuntu-latest
    name: Configurar Protección de Ramas
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Configurar protección de rama MAIN
      uses: actions/github-script@v7
      with:
        script: |
          console.log('?? Iniciando configuración de protección de ramas...');
          
          // Configurar protección para rama MAIN
          try {
            await github.rest.repos.updateBranchProtection({
              owner: 'consultasiarteq-commits',
              repo: 'oposia',
              branch: 'main',
              required_status_checks: {
                strict: true,
                contexts: []
              },
              enforce_admins: false,
              required_pull_request_reviews: {
                required_approving_review_count: 1,
                dismiss_stale_reviews: true,
                require_code_owner_reviews: false,
                require_last_push_approval: false
              },
              restrictions: null,
              required_linear_history: false,
              allow_force_pushes: false,
              allow_deletions: false,
              block_creations: false,
              required_conversation_resolution: false
            });
            console.log('? Protección de rama MAIN configurada exitosamente');
          } catch (error) {
            console.log('?? Error configurando protección MAIN:', error.message);
          }
          
          // Configurar protección para rama DEVELOP
          try {
            await github.rest.repos.updateBranchProtection({
              owner: 'consultasiarteq-commits',
              repo: 'oposia',
              branch: 'develop',
              required_status_checks: {
                strict: false,
                contexts: []
              },
              enforce_admins: false,
              required_pull_request_reviews: null,
              restrictions: null,
              required_linear_history: false,
              allow_force_pushes: true,
              allow_deletions: false,
              block_creations: false,
              required_conversation_resolution: false
            });
            console.log('? Protección de rama DEVELOP configurada exitosamente');
          } catch (error) {
            console.log('?? Error configurando protección DEVELOP:', error.message);
          }
          
    - name: Verificar configuración
      run: |
        echo "?? Configuración de protección de ramas completada"
        echo "?? Rama MAIN: Protección máxima activada"
        echo "?? Rama DEVELOP: Protección media activada"
        echo "? Repositorio listo para desarrollo empresarial"

# Workflow configurado automáticamente por Cursor AI
# Proyecto: OposIA v2.0 - IArteQ Desarrollos
# Fecha: 2025
